# Generated by Django 4.0.5 on 2022-07-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
